//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFitnessProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sporEntities : DbContext
    {
        public sporEntities()
            : base("name=sporEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminGiri> adminGiris { get; set; }
        public virtual DbSet<branslar> branslars { get; set; }
        public virtual DbSet<demirbaslar> demirbaslars { get; set; }
        public virtual DbSet<hocalar> hocalars { get; set; }
        public virtual DbSet<kategoriler> kategorilers { get; set; }
        public virtual DbSet<paketler> paketlers { get; set; }
        public virtual DbSet<programlar> programlars { get; set; }
        public virtual DbSet<satislar> satislars { get; set; }
        public virtual DbSet<silinen_Uyeler> silinen_Uyeler { get; set; }
        public virtual DbSet<sirketBilgileri> sirketBilgileris { get; set; }
        public virtual DbSet<uyeler> uyelers { get; set; }
        public virtual DbSet<yorumlar> yorumlars { get; set; }
    
        public virtual ObjectResult<demirbasGetir_Result> demirbasGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<demirbasGetir_Result>("demirbasGetir");
        }
    
        public virtual ObjectResult<demirbasRapor_Result> demirbasRapor(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<demirbasRapor_Result>("demirbasRapor", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual int ekleme(Nullable<int> kullaniciID, string baslik, string icerik, Nullable<int> hocaID)
        {
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("kullaniciID", kullaniciID) :
                new ObjectParameter("kullaniciID", typeof(int));
    
            var baslikParameter = baslik != null ?
                new ObjectParameter("baslik", baslik) :
                new ObjectParameter("baslik", typeof(string));
    
            var icerikParameter = icerik != null ?
                new ObjectParameter("icerik", icerik) :
                new ObjectParameter("icerik", typeof(string));
    
            var hocaIDParameter = hocaID.HasValue ?
                new ObjectParameter("hocaID", hocaID) :
                new ObjectParameter("hocaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ekleme", kullaniciIDParameter, baslikParameter, icerikParameter, hocaIDParameter);
        }
    
        public virtual ObjectResult<getSatis_Result> getSatis(string tcNO)
        {
            var tcNOParameter = tcNO != null ?
                new ObjectParameter("tcNO", tcNO) :
                new ObjectParameter("tcNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSatis_Result>("getSatis", tcNOParameter);
        }
    
        public virtual ObjectResult<getUye_Result> getUye(string tcNO)
        {
            var tcNOParameter = tcNO != null ?
                new ObjectParameter("tcNO", tcNO) :
                new ObjectParameter("tcNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUye_Result>("getUye", tcNOParameter);
        }
    
        public virtual int guncelleme(string mail, string telefon, string cep, string adres, string sifre)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var cepParameter = cep != null ?
                new ObjectParameter("cep", cep) :
                new ObjectParameter("cep", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("guncelleme", mailParameter, telefonParameter, cepParameter, adresParameter, sifreParameter);
        }
    
        public virtual ObjectResult<hocaGetirPro_Result> hocaGetirPro(string brns)
        {
            var brnsParameter = brns != null ?
                new ObjectParameter("brns", brns) :
                new ObjectParameter("brns", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocaGetirPro_Result>("hocaGetirPro", brnsParameter);
        }
    
        public virtual ObjectResult<hocalarRapor_Result> hocalarRapor(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocalarRapor_Result>("hocalarRapor", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<satislar> hocayaAitUyeGetirme(Nullable<int> hocaID)
        {
            var hocaIDParameter = hocaID.HasValue ?
                new ObjectParameter("hocaID", hocaID) :
                new ObjectParameter("hocaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<satislar>("hocayaAitUyeGetirme", hocaIDParameter);
        }
    
        public virtual ObjectResult<satislar> hocayaAitUyeGetirme(Nullable<int> hocaID, MergeOption mergeOption)
        {
            var hocaIDParameter = hocaID.HasValue ?
                new ObjectParameter("hocaID", hocaID) :
                new ObjectParameter("hocaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<satislar>("hocayaAitUyeGetirme", mergeOption, hocaIDParameter);
        }
    
        public virtual ObjectResult<IDdenUyeGetir_Result> IDdenUyeGetir(Nullable<int> uyeid)
        {
            var uyeidParameter = uyeid.HasValue ?
                new ObjectParameter("uyeid", uyeid) :
                new ObjectParameter("uyeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDdenUyeGetir_Result>("IDdenUyeGetir", uyeidParameter);
        }
    
        public virtual int newProUyeGuncelle(Nullable<int> id, string adi, string soyadi, string telefon, string tc, string mail, Nullable<byte> cinsiyet, Nullable<System.DateTime> tarih, Nullable<System.DateTime> dogumTarihi, string adres)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adiParameter = adi != null ?
                new ObjectParameter("adi", adi) :
                new ObjectParameter("adi", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("soyadi", soyadi) :
                new ObjectParameter("soyadi", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var cinsiyetParameter = cinsiyet.HasValue ?
                new ObjectParameter("cinsiyet", cinsiyet) :
                new ObjectParameter("cinsiyet", typeof(byte));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("dogumTarihi", dogumTarihi) :
                new ObjectParameter("dogumTarihi", typeof(System.DateTime));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("newProUyeGuncelle", idParameter, adiParameter, soyadiParameter, telefonParameter, tcParameter, mailParameter, cinsiyetParameter, tarihParameter, dogumTarihiParameter, adresParameter);
        }
    
        public virtual ObjectResult<paketlerRapor_Result> paketlerRapor(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paketlerRapor_Result>("paketlerRapor", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<prcListele_Result> prcListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcListele_Result>("prcListele");
        }
    
        public virtual ObjectResult<pro_BransGetir_Result> pro_BransGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_BransGetir_Result>("pro_BransGetir");
        }
    
        public virtual ObjectResult<proMail_Result> proMail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proMail_Result>("proMail");
        }
    
        public virtual ObjectResult<proUyeIDAra_Result> proUyeIDAra(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proUyeIDAra_Result>("proUyeIDAra", idParameter);
        }
    
        public virtual ObjectResult<string> resimPro(Nullable<int> gelenID)
        {
            var gelenIDParameter = gelenID.HasValue ?
                new ObjectParameter("gelenID", gelenID) :
                new ObjectParameter("gelenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("resimPro", gelenIDParameter);
        }
    
        public virtual ObjectResult<Satis_Ara_Result> Satis_Ara(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Satis_Ara_Result>("Satis_Ara", araParameter);
        }
    
        public virtual ObjectResult<Satislari_Getir_Result> Satislari_Getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Satislari_Getir_Result>("Satislari_Getir");
        }
    
        public virtual ObjectResult<sifreGetir_Result> sifreGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sifreGetir_Result>("sifreGetir");
        }
    
        public virtual ObjectResult<sirketbilgilergetir_Result> sirketbilgilergetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sirketbilgilergetir_Result>("sirketbilgilergetir");
        }
    
        public virtual int updUyelik(Nullable<int> satisID, Nullable<decimal> satisFiyat, Nullable<System.DateTime> satisTarih)
        {
            var satisIDParameter = satisID.HasValue ?
                new ObjectParameter("satisID", satisID) :
                new ObjectParameter("satisID", typeof(int));
    
            var satisFiyatParameter = satisFiyat.HasValue ?
                new ObjectParameter("satisFiyat", satisFiyat) :
                new ObjectParameter("satisFiyat", typeof(decimal));
    
            var satisTarihParameter = satisTarih.HasValue ?
                new ObjectParameter("satisTarih", satisTarih) :
                new ObjectParameter("satisTarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updUyelik", satisIDParameter, satisFiyatParameter, satisTarihParameter);
        }
    
        public virtual ObjectResult<Uye_Ara_Result> Uye_Ara(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Uye_Ara_Result>("Uye_Ara", araParameter);
        }
    
        public virtual ObjectResult<uyedataGetir_Result> uyedataGetir(Nullable<int> uyeID)
        {
            var uyeIDParameter = uyeID.HasValue ?
                new ObjectParameter("uyeID", uyeID) :
                new ObjectParameter("uyeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uyedataGetir_Result>("uyedataGetir", uyeIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> uyeIDAra(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("uyeIDAra", araParameter);
        }
    
        public virtual ObjectResult<Uyeleri_Getir_Result> Uyeleri_Getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Uyeleri_Getir_Result>("Uyeleri_Getir");
        }
    
        public virtual ObjectResult<uyelerRapor_Result> uyelerRapor(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uyelerRapor_Result>("uyelerRapor", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual int Uyelik_Aktar(Nullable<int> alanID, Nullable<int> satisID)
        {
            var alanIDParameter = alanID.HasValue ?
                new ObjectParameter("alanID", alanID) :
                new ObjectParameter("alanID", typeof(int));
    
            var satisIDParameter = satisID.HasValue ?
                new ObjectParameter("satisID", satisID) :
                new ObjectParameter("satisID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Uyelik_Aktar", alanIDParameter, satisIDParameter);
        }
    
        public virtual int uyelikDondur(Nullable<int> uyeID)
        {
            var uyeIDParameter = uyeID.HasValue ?
                new ObjectParameter("uyeID", uyeID) :
                new ObjectParameter("uyeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uyelikDondur", uyeIDParameter);
        }
    }
}
