//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFitnessProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        public int satisID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> paketID { get; set; }
        public Nullable<int> hocaID { get; set; }
        public Nullable<byte> odemeTuru { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<System.DateTime> baslamaTarih { get; set; }
        public Nullable<System.DateTime> bitisTarihi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
